#SpringBoot schaut als  erstes nach einem application.yml file, darum dieses immmer als erstes erstellen
#die abstände sind sehr wichtig, sonst wird das file nicht gelesen
#keine tabs verwenden, 2 oder 4 leerzeichen

guru:
  jms:
    username: Bart Simpson
    password: EatMyShorts
    url: www.howToBully.com


---
#die drei striche bedeuten das ein neues file begonnen wird
#der programmfluss wird in das zweite file weitergeleitet da das deutsche profil im application.properties aktiv ist

spring:
  profiles: de
guru:
  jms:
    url: www.howToBully.com $$$$ german

